"""add welcome_seen

Revision ID: 1a3621aa2d1c
Revises: 9c442be0c8ad
Create Date: 2026-07-07 14:57:24.236962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3621aa2d1c'
down_revision: Union[str, Sequence[str], None] = '9c442be0c8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "welcome_seen",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()))
    op.alter_column(
        "user_profiles",
        "welcome_seen",
        server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'welcome_seen')
    # ### end Alembic commands ###
