"""initial schema

Revision ID: 2ebfcf45d15b
Revises: 
Create Date: 2026-05-27 20:00:52.060162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ebfcf45d15b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_events', 'event_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('analytics_events', 'event_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.add_column('daily_analytics', sa.Column('activation_rate', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('rebalance_adoption', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('ai_engagement_rate', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('auto_invest_conversion', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('avg_portfolio_size', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('avg_goals_per_user', sa.Float(), nullable=False))
    op.add_column('daily_analytics', sa.Column('churn_risk_rate', sa.Float(), nullable=False))
    op.alter_column('market_assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_market_assets_updated_at'), 'market_assets', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=True)
    op.alter_column('owners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_portfolios_updated_at'), 'portfolios', ['updated_at'], unique=False)
    op.alter_column('shariah_screens', 'screened_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_fundamentals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profiles', 'first_goal_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_analysis_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_rebalance_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_auto_invest_done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'first_auto_invest_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_rebalance_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_analysis_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'first_goal_done',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_fundamentals', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shariah_screens', 'screened_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portfolios_updated_at'), table_name='portfolios')
    op.alter_column('portfolios', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('owners', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=False)
    op.drop_index(op.f('ix_market_assets_updated_at'), table_name='market_assets')
    op.alter_column('market_assets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('daily_analytics', 'churn_risk_rate')
    op.drop_column('daily_analytics', 'avg_goals_per_user')
    op.drop_column('daily_analytics', 'avg_portfolio_size')
    op.drop_column('daily_analytics', 'auto_invest_conversion')
    op.drop_column('daily_analytics', 'ai_engagement_rate')
    op.drop_column('daily_analytics', 'rebalance_adoption')
    op.drop_column('daily_analytics', 'activation_rate')
    op.alter_column('analytics_events', 'event_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('analytics_events', 'event_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###