"""add welcome_completed

Revision ID: 9c442be0c8ad
Revises: d75058959de8
Create Date: 2026-06-30 12:26:41.521875

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c442be0c8ad'
down_revision: Union[str, Sequence[str], None] = 'd75058959de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("user_profiles", sa.Column("welcome_completed",
        sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column("user_profiles", "welcome_completed",
        server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'welcome_completed')
    # ### end Alembic commands ###
