"""add referral tables

Revision ID: ac241613ba6c
Revises: 1a3621aa2d1c
Create Date: 2026-07-11 10:09:02.496202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac241613ba6c'
down_revision: Union[str, Sequence[str], None] = '1a3621aa2d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_codes',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('reward_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.tg_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_referral_codes_code'), 'referral_codes', ['code'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_id', sa.BigInteger(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_id'], ['owners.tg_id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['owners.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invited_id')
    )
    op.create_index(op.f('ix_referrals_inviter_id'), 'referrals', ['inviter_id'], unique=False)
    op.create_table('user_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('admin_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['owners.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reviews_user_id'), 'user_reviews', ['user_id'], unique=False)
    op.drop_constraint(op.f('goals_portfolio_id_fkey'), 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key(op.f('goals_portfolio_id_fkey'), 'goals', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_index(op.f('ix_user_reviews_user_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_referrals_inviter_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_codes_code'), table_name='referral_codes')
    op.drop_table('referral_codes')
    # ### end Alembic commands ###
