"""add fundamentals fields

Revision ID: d75058959de8
Revises: 2ebfcf45d15b
Create Date: 2026-06-14 20:46:50.839735

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd75058959de8'
down_revision: Union[str, Sequence[str], None] = '2ebfcf45d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_fundamentals', sa.Column('total_debt', sa.Float(), nullable=True))
    op.drop_constraint(op.f('user_profiles_portfolio_id_fkey'), 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'risk_tolerance')
    op.drop_column('user_profiles', 'auto_invest_enabled')
    op.drop_column('user_profiles', 'last_auto_invest')
    op.drop_column('user_profiles', 'next_auto_invest_at')
    op.drop_column('user_profiles', 'portfolio_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('next_auto_invest_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_auto_invest', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('auto_invest_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('risk_tolerance', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_profiles_portfolio_id_fkey'), 'user_profiles', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_column('stock_fundamentals', 'total_debt')
    # ### end Alembic commands ###
